name: "\U0001F41E Bug report"
description: Report an issue with this library
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: reproduction
    attributes:
      label: Reproduction
      description: "If possible, provide a boiled down editable reproduction with minimal dependencies (avoid testing, linting, and other unrelated dependencies). A failing unit test is even better! Otherwise provide as much information as possible to reproduce the problem. If no reproduction is provided and the information is not enough to reproduce the problem, we won't be able to give it a look **and the issue will be closed**."
      placeholder: Reproduction
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce the bug
      description: |
        1. Click on ...
        2. Check logs
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: 'A clear and concise description of what actually happens.'
    validations:
      required: true
  - type: textarea
    id: other-info
    attributes:
      label: Additional information
      description: Add any other context about the problem here.
  - type: markdown
    attributes:
      value: |
        ## Before creating an issue make sure that:
        - This hasn't been [reported before](/issues).
        - The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug **with no external dependencies** (e.g. vuetify, pinia).
