blank_issues_enabled: false
contact_links:
  - name: Question
    url: /discussions/new?category=Q-A
    about: Ask a question or discuss about this library
  - name: Ideas
    url: /discussions/new?category=Ideas
    about: Start a discussion to improve this library
  - name: GitHub Sponsors
    url: https://github.com/sponsors/anburocky3
    about: Like this project? Please consider supporting the author.
